# Pre-commit hooks for Virtual Dietitian
# Install: pip install pre-commit
# Setup: pre-commit install

repos:
  # Code formatting with Black
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.12
        args: ['--line-length=100']

  # Linting and import sorting with Ruff (replaces flake8 + isort)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      # Run the linter
      - id: ruff
        args: ['--fix', '--line-length=100']
      # Run the formatter (optional, can replace black eventually)
      - id: ruff-format
        args: ['--line-length=100']

  # Type checking with mypy (non-blocking for gradual adoption)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args: ['--config-file=pyproject.toml']
        additional_dependencies: ['types-requests']
        verbose: true
        # Allow commits even if mypy finds issues (gradual adoption)
        # Run manually with: pre-commit run mypy --all-files
        stages: [manual]

  # Standard file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']
