# Python project configuration for Virtual Dietitian

[tool.black]
line-length = 100
target-version = ['py312']
include = '\.pyi?$'
extend-exclude = '''
/(
    \.git
  | \.venv
  | \.env
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 100
skip_gitignore = true

[tool.ruff]
# Same line length as black
line-length = 100
target-version = "py312"

# Exclude directories
extend-exclude = [
    ".git",
    ".venv",
    ".env",
    "build",
    "dist",
]

[tool.ruff.lint]
# Enable these rule categories
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort (import sorting)
    "N",   # pep8-naming
    "UP",  # pyupgrade
]

# Ignore rules that conflict with black or are too strict
ignore = []

[tool.ruff.lint.isort]
# Black-compatible import sorting
force-single-line = false
force-sort-within-sections = false

[tool.pytest.ini_options]
testpaths = ["tests", "cloud-functions/nutrition-analyzer"]
python_files = "test_*.py"
python_functions = "test_*"
addopts = "-v --cov=cloud-functions --cov-report=term-missing"

[tool.coverage.run]
omit = [
    "*/usda_client.py",  # USDA API integration disabled (feature flag off)
]

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false  # Gradual adoption
check_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_optional = true

# Exclude directories
exclude = [
    'venv/',
    '.venv/',
    'build/',
    'dist/',
]

[tool.bandit]
exclude_dirs = [
    "tests/",
    "venv/",
    ".venv/",
]
# Lightweight pre-commit: only high severity
# Comprehensive CI/CD: all severities
skips = [
    "B101",  # assert_used - common in tests (but tests/ excluded anyway)
]
