name: Security Scan

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    # Run weekly security scans on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit[toml] safety

      - name: Run Bandit security scan (comprehensive)
        run: |
          bandit -r cloud-functions/ scripts/ -f json -o bandit-report.json || true
          bandit -r cloud-functions/ scripts/ -f txt
        continue-on-error: true

      - name: Run Safety dependency check
        run: |
          safety check -r cloud-functions/nutrition-analyzer/requirements.txt --json --output safety-report.json || true
          safety check -r cloud-functions/nutrition-analyzer/requirements.txt
        continue-on-error: true

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-reports
          path: |
            bandit-report.json
            safety-report.json
          retention-days: 30
